### ISSUE TITLE
[Getter("api/{id}")] httpMethod can work with string interpolation as ASP.NET Core

### ISSUE THREAD

**Issue by dotnetgoo** [tigernetframework/Tigernet#1]

**Comment by ahmedanwar100** [comment]
@Rashidovicc can you help me in this a little bit as I am a bit unclear on this

**Comment by ahmedanwar100** [comment]
I have explored the AspnetCore official GitHub repo and Routing module documentation and discovered that `UseRouting` middleware is responsible for loading the routes on startup and matching with the appropriate one when a request comes.
Here is the AspnetCore Routing project 
https://github.com/dotnet/aspnetcore/tree/main/src/Http/Routing
![image](https://user-images.githubusercontent.com/35097422/232564175-84d36da3-c79f-44ea-8df3-a635f69cc9af.png)

**Comment by ahmedanwar100** [comment]
@dotnetgoo, can we get some help from the Aspnet Core team to help us implement the Routing feature in Tigernet? We should think this Routing module as one of our main modules(as you know) so a proper solution should be built for this part

**Comment by dotnetgoo** [comment]
@ahmedanwar100 I’ll try to get help from ASP.NET Core team

**Comment by ahmedanwar100** [comment]
Great
