### ISSUE TITLE
Create builder.MapResters() method for appending resters (controllers) to route dictionary.

### ISSUE THREAD

**Issue by dotnetgoo** [tigernetframework/Tigernet#3]
Currently, we can registrate our routes only one by one, such as following:
builder.MapRester<UsersRester>();
builder.MapRester<HomeRester>();

You should add new features about mapping, that is builder.MapResters()...

Rester is similar with controller as asp.net core

**Comment by sokhibjaynarov** [comment]
I created pull request for this issue. Can you check it?
