### ISSUE TITLE
Create or Update the pipeline to build and deploy the dev branch after merging and undo the changes if something fails 

### ISSUE THREAD

**Issue by ahmedanwar100** [tigernetframework/Tigernet#64]
Recently, we have faced an issue #63 and to avoid such issues in the future we should create or update a pipeline that will build and run(or deploy) the dev branch, and if there is any issue we will undo the changes and move the dev branch to the stable state

**Comment by orzklv** [comment]
Closing the issue temporarily. I've added many addons like test/buils and also github's builtin codeQL analysis. There are many solutions, but as project doesn't have sponsor at the moment, we won't be able to afford any of those fancy tools.
